# Generated by Django 4.2.1 on 2023-07-13 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('idBoleta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaBoleta', models.DateField()),
                ('montoPagoBoleta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='caso',
            fields=[
                ('idCaso', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCaso', models.DateField()),
                ('descripcionCaso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('runCliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=20)),
                ('correoCliente', models.EmailField(max_length=20)),
                ('contraseñaCliente', models.CharField(max_length=15)),
                ('apPaternoCliente', models.CharField(max_length=20)),
                ('apMaternoCliente', models.CharField(max_length=20)),
                ('direccionCliente', models.CharField(max_length=20)),
                ('telefonoCliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('idContrato', models.AutoField(primary_key=True, serialize=False)),
                ('fechaContrato', models.DateField()),
                ('montoContrato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoEmpleado',
            fields=[
                ('idTipoEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoEmpleado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='solicitud_aceptada',
            fields=[
                ('idSolicitudAceptada', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionSolicitudAceptada', models.CharField(max_length=100)),
                ('fechaSolicitudAceptada', models.DateField()),
                ('presupuestoSolicitudAceptada', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionSolicitud', models.CharField(max_length=100)),
                ('fechaSolicitud', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField()),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.boleta')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('runEmpleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreEmpleado', models.CharField(max_length=20)),
                ('apPaternoEmpleado', models.CharField(max_length=20)),
                ('apMaternoEmpleado', models.CharField(max_length=20)),
                ('contraseñaEmpleado', models.CharField(max_length=15)),
                ('tipoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.tipoempleado')),
            ],
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('idDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionDocumento', models.CharField(max_length=20)),
                ('archivoDocumento', models.FileField(upload_to='documentos/')),
                ('fechaDocumento', models.DateField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.caso')),
            ],
        ),
        migrations.CreateModel(
            name='diligencia',
            fields=[
                ('idDiligencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionDiligencia', models.CharField(max_length=100)),
                ('fechaDiligencia', models.DateField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.caso')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.comuna'),
        ),
        migrations.AddField(
            model_name='caso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.cliente'),
        ),
        migrations.AddField(
            model_name='caso',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.contrato'),
        ),
        migrations.AddField(
            model_name='caso',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.empleado'),
        ),
    ]
